# -*- coding: utf-8 -*-
"""deployed_app_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwHk7EKLj2vuUsF2pcBdKWR7YeQloROP
"""

import streamlit as st

def find_largest_number(a, b, c):
    largest = max(a, b, c)
    return largest

st.title("Find the Largest Number")

st.write("Enter three numbers to find the largest one:")

num1 = st.number_input("Enter the first number:")
num2 = st.number_input("Enter the second number:")
num3 = st.number_input("Enter the third number:")

if st.button("Find Largest"):
    largest = find_largest_number(num1, num2, num3)
    st.write(f"The largest number is: {largest}")

